### ISSUE TITLE
Conflict with Customizer?

### ISSUE THREAD

**Issue by arielsfr** [r-a-y/buddypress-followers#70]
The Wordpress Customizer (WP 4.4) gets stuck with a "Please wait. Customizer Loading..." message and never finishes loading. It works properly, however, when BuddyPress Follow is deactivated.

**Comment by arielsfr** [comment]
UPDATE: ... but Customizer works fine when Follow is the only active plugin.

**Comment by r-a-y** [comment]
Thanks for posting, but I cannot duplicate this on both v1.2.1 and v1.3-bleeding.

In your second post you say that Customizer works when Follow is activated, so that leads me to believe your issue stems from another plugin.

Closing for now, but feel free to reopen if you have other details to replicate the problem.
